ALTER TABLE drivers
    ADD COLUMN revision BIGINT NOT NULL DEFAULT 0;

ALTER TABLE vehicles
    ADD COLUMN revision BIGINT NOT NULL DEFAULT 0;

ALTER TABLE trips
    ADD COLUMN revision BIGINT NOT NULL DEFAULT 0;
